import type { Metadata } from "next";
import { JetBrains_Mono } from "next/font/google";
import "./globals.css";

import { UserProvider } from "@/providers/ctx";

const jetbrainsmono = JetBrains_Mono({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<UserProvider>
			<head>
				<title>.nidhi - valentine</title>
			</head>
			<html lang="en">
				<body className={jetbrainsmono.className}>{children}</body>
			</html>
		</UserProvider>
	);
}
